version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - /data/postgres:/data/postgres
    env_file:
    - docker.env
    networks:
    - postgres

  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - /data/pgadmin:/root/.pgadmin
    env_file:
    - docker.env
    networks:
    - postgres

  app: ## nome do serviço
    build: . ## localização do dockerfile
    command: yarn dev ## comando a executar
    ports:
      - "3333:3333" ## redirecionamento de porta quando chegar alguma requisição na porta 3000 chama o container na porta 3000
    depends_on:
        - postgres
    volumes:
      - .:/usr/app ## monitoro a pasta atual . e envio as alterações para /usr/app
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
